# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  primary:
    <<: *default
    database: rimborsi_development
  rails_pulse:
    adapter: sqlite3
    database: storage/development_rails_pulse.sqlite3
    migrations_paths: db/rails_pulse_migrate
    schema_dump: false

test:
  primary:
    <<: *default
    database: rimborsi_test
  rails_pulse:
    adapter: sqlite3
    database: storage/test_rails_pulse.sqlite3
    migrations_paths: db/rails_pulse_migrate
    schema_dump: false

staging:
  primary:
    <<: *default
    database: rimborsi_production
    username: rimborsi
    password: <%= ENV["RIMBORSI_DATABASE_PASSWORD"] %>
  rails_pulse:
    adapter: sqlite3
    database: storage/staging_rails_pulse.sqlite3
    migrations_paths: db/rails_pulse_migrate
    schema_dump: false

production:
  primary:
    adapter: mysql2
    encoding: utf8mb4
    database: rimborsi_db
    pool: 5
    username: rimborsi
    password: <%= ENV["MYSQL_PASSWORD"] %>
    socket: /run/mysqld/mysqld.sock
  rails_pulse:
    adapter: sqlite3
    database: storage/production_rails_pulse.sqlite3
    migrations_paths: db/rails_pulse_migrate
    schema_dump: false
